[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
